/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useSpring, a } from '@react-spring/three';

export default function Model(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/shoes-adidas.glb')

    useFrame(() => group.current.rotation.y += 0.008)

    const [expand, setExpand] = useState(false);

    const spring = useSpring({
        scale: expand ? 2 : 1
    })

    return (
        <a.group ref={group} {...props} dispose={null} onClick={() => setExpand(!expand)} scale={spring.scale}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.shoeotherparts.geometry}
                material={materials.Mat_1}
                position={[-0.72, 0.02, 1.01]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.01, 0.01, 0.01]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.stripes.geometry}
                material={materials['Default OBJ']}
                position={[-0.72, 0.02, 1.01]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.01, 0.01, 0.01]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.shoebody.geometry}
                material={materials.Material}
                position={[-0.72, 0.02, 1.01]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.01, 0.01, 0.01]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle.geometry}
                material={materials['floor-material']}
                scale={[6.8, 6.8, 6.8]}
            />
        </a.group>
    )
}

useGLTF.preload('/shoes-adidas.glb')